INSERT INTO "currency" ("alpha_3_code", "name_rus", "name_eng", "num_code")
    VALUES ('AUD', 'Австралийский доллар', 'Australian Dollar', 36),
           ('DZD', 'Алжирский динар', 'Algerian Dinar', 12),
           ('ARS', 'Аргентинский песо', 'Argentine Peso', 32),
           ('AFN', 'Афгани', 'Afghani', 971),
           ('BSD', 'Багамский доллар', 'Bahamian Dollar', 44),
           ('PAB', 'Бальбоа', 'Balboa', 590),
           ('BBD', 'Барбадосский доллар', 'Barbados Dollar', 52),
           ('THB', 'Бат', 'Baht', 764),
           ('BZD', 'Белизский доллар', 'Belize Dollar', 84),
           ('BMD', 'Бермудский доллар', 'Bermudian Dollar', 60),
           ('ETB', 'Бирр', 'Ethiopian Birr', 230),
           ('BGN', 'Болгарский лев', 'Bulgarian Lev', 975),
           ('VEF', 'Боливар', 'Bolivar', 937),
           ('BOB', 'Боливиано', 'Boliviano', 68),
           ('BRL', 'Бразильский реал', 'Brazilian Real', 986),
           ('BND', 'Брунейский доллар', 'Brunei Dollar', 96),
           ('BIF', 'Бурундийский Франк', 'Burundi Franc', 108),
           ('VUV', 'Вату', 'Vatu', 548),
           ('KRW', 'Вон', 'Won', 410),
           ('XCD', 'Восточно-карибский доллар', 'East Caribbean Dollar', 951),
           ('GYD', 'Гайнаский доллар', 'Guyana Dollar', 328),
           ('GNF', 'Гвинейский франк', 'Guinea Franc', 324),
           ('GIP', 'Гибралтарский фунт', 'Gibraltar Pound', 292),
           ('HKD', 'Гонконгский доллар', 'Hong Kong Dollar', 344),
           ('UAH', 'Гривна', 'Hryvnia', 980),
           ('PYG', 'Гуарани', 'Guarani', 600),
           ('HTG', 'Гурд', 'Gourde', 332),
           ('GMD', 'Даласи', 'Dalasi', 270),
           ('DKK', 'Датская крона', 'Danish Krone', 208),
           ('MKD', 'Денар', 'Denar', 807),
           ('DJF', 'Джибутский Франк', 'Djibouti Franc', 262),
           ('BHD', 'Динар', 'Bahraini Dinar', 48),
           ('AED', 'Дирхам', 'UAE Dirham', 784),
           ('KYD', 'Доллар Каймановых Островов', 'Cayman Islands Dollar', 136),
           ('USD', 'Доллар США', 'US Dollar', 840),
           ('TTD', 'Доллар Тринидада и Тобаго', 'Trinidad and Tobago Dollar', 780),
           ('DOP', 'Доминиканский песо', 'Dominican Peso', 214),
           ('VND', 'Донг', 'Dong', 704),
           ('AMD', 'Драхм', 'Armenian Dram', 51),
           ('EUR', 'Евро', 'Euro', 978),
           ('EGP', 'Египетский фунт', 'Egyptian Pound', 818),
           ('ZMW', 'Замбийская квача', 'Zambian Kwacha', 967),
           ('ZWL', 'Зимбабвийский доллар', 'Zimbabwe Dollar', 932),
           ('INR', 'Индийская рупия', 'Indian Rupee', 356),
           ('JOD', 'Иорданский динар', 'Jordanian Dinar', 400),
           ('IQD', 'Иракский динар', 'Iraqi Dinar', 368),
           ('IRR', 'Иранский риал', 'Iranian Rial', 364),
           ('ISK', 'Исландская крона', 'Iceland Krona', 352),
           ('JPY', 'Йена', 'Yen', 392),
           ('CAD', 'Канадский доллар', 'Canadian Dollar', 124),
           ('QAR', 'Катарский риал', 'Qatari Rial', 634),
           ('AOA', 'Кванза', 'Kwanza', 973),
           ('MWK', 'Квача', 'Kwacha', 454),
           ('KES', 'Кенийский шиллинг', 'Kenyan Shilling', 404),
           ('GTQ', 'Кетсаль', 'Quetzal', 320),
           ('PGK', 'Кина', 'Kina', 598),
           ('LAK', 'Кип', 'Kip', 418),
           ('CNY', 'Китайский юань', 'Yuan Renminbi', 156),
           ('CRC', 'Колон', 'Costa Rican Colon', 188),
           ('COP', 'Колумбийский песо', 'Colombian Peso', 170),
           ('KMF', 'Коморский франк', 'Comoro Franc', 174),
           ('BAM', 'Конвертируемая марка', 'Convertible Mark', 977),
           ('CUC', 'Конвертируемый песо', 'Peso Convertible', 931),
           ('CDF', 'Конголезский франк', 'Congolese Franc', 976),
           ('NIO', 'Кордоба', 'Cordoba Oro', 558),
           ('KWD', 'Кувейтский динар', 'Kuwaiti Dinar', 414),
           ('HRK', 'Куна', 'Kuna', 191),
           ('XPF', 'КФП Франк', 'CFP Franc', 953),
           ('MMK', 'Кьят', 'Kyat', 104),
           ('GEL', 'Лари', 'Lari', 981),
           ('ALL', 'Лек', 'Lek', 8),
           ('HNL', 'Лемпира', 'Lempira', 340),
           ('SLL', 'Леоне', 'Leone', 694),
           ('LRD', 'Либерийский доллар', 'Liberian Dollar', 430),
           ('LBP', 'Ливанский фунт', 'Lebanese Pound', 422),
           ('LYD', 'Ливийский динар', 'Libyan Dinar', 434),
           ('SZL', 'Лилангени', 'Lilangeni', 748),
           ('LSL', 'Лоти', 'Loti', 426),
           ('MUR', 'Маврикийская рупия', 'Mauritius Rupee', 480),
           ('MGA', 'Малагасийский ариари', 'Malagasy Ariary', 969),
           ('MYR', 'Малайзийский рингит', 'Malaysian Ringgit', 458),
           ('AZN', 'Манат', 'Azerbaijanian Manat', 944),
           ('MAD', 'Марокканский дирхам', 'Moroccan Dirham', 504),
           ('BOV', 'Мвдол', 'Mvdol', 984),
           ('MXN', 'Мексиканский песо', 'Mexican Peso', 484),
           ('MZN', 'Мозамбикский метикал', 'Mozambique Metical', 943),
           ('NGN', 'Наира', 'Naira', 566),
           ('ERN', 'Накфа', 'Nakfa', 232),
           ('NAD', 'Намибийский доллар', 'Namibia Dollar', 516),
           ('BTN', 'Нгултрум', 'Ngultrum', 64),
           ('NPR', 'Непальская рупия', 'Nepalese Rupee', 524),
           ('ANG', 'Нидерландский антильский гульден', 'Netherlands Antillean Guilder', 532),
           ('NZD', 'Новозеландский доллар', 'New Zealand Dollar', 554),
           ('ILS', 'Новый израильский шекель', 'New Israeli Sheqel', 376),
           ('PEN', 'Новый соль', 'Nuevo Sol', 604),
           ('TWD', 'Новый тайваньский доллар', 'New Taiwan Dollar', 901),
           ('TMT', 'Новый туркменский манат', 'Turkmenistan New Manat', 934),
           ('NOK', 'Норвежская крона', 'Norwegian Krone', 578),
           ('OMR', 'Оманский риал', 'Rial Omani', 512),
           ('TOP', 'Паанга', 'Pa’anga', 776),
           ('PKR', 'Пакистанская рупия', 'Pakistan Rupee', 586),
           ('MOP', 'Патака', 'Pataca', 446),
           ('RON', 'Румынский Лей', 'Romanian Leu', 946),
           ('BWP', 'Пула', 'Pula', 72),
           ('ZAR', 'Ранд', 'Rand', 710),
           ('YER', 'Риал', 'Yemeni Rial', 886),
           ('KHR', 'Риель', 'Riel', 116),
           ('SAR', 'Риял', 'Saudi Riyal', 682),
           ('RUB', 'Российский рубль', 'Russian Ruble', 643),
           ('IDR', 'Рупия', 'Rupiah', 360),
           ('MVR', 'Руфия', 'Rufiyaa', 462),
           ('SVC', 'Сальвадорский колон', 'El Salvador Colon', 222),
           ('KPW', 'Северо-корейский вон', 'North Korean Won', 408),
           ('GHS', 'Седи', 'Ghana Cedi', 936),
           ('RSD', 'Сербиский динар', 'Serbian Dinar', 941),
           ('SGD', 'Сингапурский доллар', 'Singapore Dollar', 702),
           ('SYP', 'Сирийский фунт', 'Syrian Pound', 760),
           ('PLN', 'Слотый', 'Zloty', 985),
           ('SBD', 'Соломонский доллар', 'Solomon Islands Dollar', 90),
           ('KGS', 'Сом', 'Som', 417),
           ('SOS', 'Сомалийский шиллинг', 'Somali Shilling', 706),
           ('TJS', 'Сомони', 'Somoni', 972),
           ('SDG', 'Суданский фунт', 'Sudanese Pound', 938),
           ('XSU', 'Сукре', 'Sucre', 994),
           ('SRD', 'Суринамский доллар', 'Surinam Dollar', 968),
           ('BDT', 'Така', 'Taka', 50),
           ('WST', 'Тала', 'Tala', 882),
           ('TZS', 'Танзанийский шиллинг', 'Tanzanian Shilling', 834),
           ('KZT', 'Тенге', 'Tenge', 398),
           ('MNT', 'Тугрик', 'Tugrik', 496),
           ('TND', 'Тунисский динар', 'Tunisian Dinar', 788),
           ('TRY', 'Турецкая лира', 'Turkish Lira', 949),
           ('UGX', 'Угандийский шиллинг', 'Uganda Shilling', 800),
           ('UZS', 'Узбекский сум', 'Uzbekistan Sum', 860),
           ('COU', 'Унидад де валор реаль', 'Unidad de Valor Real', 970),
           ('CLF', 'Унидад де Фоменто', 'Unidad de Fomento', 990),
           ('XUA', 'Условная единица ADB', 'ADB Unit of Account', 965),
           ('FJD', 'Фиджийский доллар', 'Fiji Dollar', 242),
           ('PHP', 'Филиппинский песо', 'Philippine Peso', 608),
           ('AWG', 'Флорин', 'Aruban Florin', 533),
           ('HUF', 'Форинт', 'Forint', 348),
           ('RWF', 'Франк', 'Rwanda Franc', 646),
           ('FKP', 'Фунт', 'Falkland Islands Pound', 238),
           ('SHP', 'Фунт Святой Елены', 'Saint Helena Pound', 654),
           ('GBP', 'Фунт Стерлингов', 'Pound Sterling', 826),
           ('CZK', 'Чешская крона', 'Czech Koruna', 203),
           ('CLP', 'Чилийский песо', 'Chilean Peso', 152),
           ('SEK', 'Шведская крона', 'Swedish Krona', 752),
           ('CHF', 'Швейцарский франк', 'Swiss Franc', 756),
           ('CVE', 'Эскудо', 'Cabo Verde Escudo', 132),
           ('SSP', 'Южно-суданский фунт', 'South Sudanese Pound', 728),
           ('JMD', 'Ямайский доллар', 'Jamaican Dollar', 388),
           ('LKR', 'Шри-ланкийская Рупия', 'Sri Lanka Rupee', 144),
           ('SCR', 'Сейшельская Рупия', 'Seychelles Rupee', 690),
           ('CUP', 'Кубинское Песо', 'Cuban Peso', 192),
           ('XOF', 'Западноафриканский франк КФА', 'West African CFA franc', 952),
           ('UYU', 'Уругвайское Песо', 'Peso Uruguayo', 858),
           ('XAF', 'Центральноафриканский франк КФА', 'Central African CFA franc', 950),
           ('MDL', 'Молдавский Лей', 'Moldovan Leu', 498);